inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'daru_lite.gemspec'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
    - '**/*.erb'
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'benchmarks/*'
    - 'profile/*'
    - 'tmp/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.4
  NewCops: enable

require:
  - rubocop-performance
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
