name: CI
on: [push]

env:
  CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
  # `github.ref` points to the *merge commit* when running tests on a pull request, which will be a commit
  # that doesn't exists in our code base. Since this workflow triggers from a PR, we use the HEAD SHA instead.
  #
  # NOTE: These are both used by Code Climate (cc-test-reporter).
  GIT_COMMIT_SHA: ${{github.event.pull_request.head.sha}}
  GIT_BRANCH: ${{github.head_ref}}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run linters
      run: |
        bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.4']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: "Download cc-test-reporter from codeclimate.com"
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: "Report to Code Climate that we will send a coverage report."
      run: ./cc-test-reporter before-build
    - name: Run tests
      run: bundle exec rspec
    - name: Upload code coverage to Code Climate
      run: |
        ./cc-test-reporter after-build \
          --coverage-input-type simplecov \
          ./coverage/.resultset.json
